### ISSUE TITLE
ids in `as.data.frame.tracks` are saved as factor

### ISSUE THREAD

**Issue by burgerga** [jtextor/MotilityLab#7]
Easy to fix, but not sure what you prefer: (1) always converting to numeric  in `as.tracks.data.frame`, or (2), allowing `as.data.frame.tracks` to be called with `stringsAsFactors = F` and passing it on to the `as.data.frame` call...

**Comment by jtextor** [comment]
I actually don't mind so much if they are saved as a factor -- isn't that also more efficient anyway? I guess the most flexible solution would be indeed passing on stringsAsFactors.

**Comment by burgerga** [comment]
No, it doesn't matter that much, it broke a some code I wrote because I failed to check for factor columns ;)
I'll make a pull request for the stringsAsFactors option.

PS I just published https://github.com/burgerga/mdftracks to CRAN, I'm planning on making MotilityLab a dependency (add S3 method write.mdf.tracks for example), because I think it could be a nice combo ;)

**Comment by jtextor** [comment]
OK since I was on it anyway, I now added an "idsAsFactors" option to the as.tracks.data.frames function.

**Comment by burgerga** [comment]
Ah thanks! But could you maybe use `stringsAsFactors = default.stringsAsFactors()` as argument to `as.data.frame.tracks`? Since it's an S3 method it's nice to keep it consistent with the `base::as.data.frame` method and by using  `default.stringsAsFactors()` the global option `options(stringsAsFactors = ...)` keeps working.
